CREATE DATABASE geodetest;

CREATE USER geodetest;

\PASSWORD geodetest;

ALTER USER geodetest WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE geodetest TO geodetest;

ALTER ROLE geodetest WITH CREATEDB CREATEROLE;

GRANT CONNECT ON DATABASE geodetest TO geodetest;

GRANT USAGE ON SCHEMA PUBLIC TO geodetest;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO geodetest;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO geodetest;

CREATE TABLE booking(USER_ID INT, STATUS VARCHAR(10));