#!/usr/bin/env bash

CREATE DATABASE railway_reservation;

CREATE USER test;

\password test;

ALTER USER test WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE railway_reservation TO test;

ALTER ROLE test WITH CREATEDB CREATEROLE;

GRANT CONNECT ON DATABASE railway_reservation TO test;

GRANT USAGE ON SCHEMA PUBLIC TO test;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO test;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO test;

\c railway_reservation;

CREATE TABLE booking(USER_ID INT, NAME VARCHAR(10));